using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace CELLRecordForwarder;

public static class Program
{
    private static Lazy<Settings> _settings = null!;

    public static Task<int> Main(string[] args)
    {
        return SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings("Settings", "Settings.json", out _settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "CELLRecordForwarder.esp")
            .Run(args);
    }

    private static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var lightingMod = _settings.Value.LightingModPlugin;
        var modIndex = state.LoadOrder.IndexOf(lightingMod);

        if (modIndex < 0 || !state.LoadOrder[modIndex].Enabled || state.LoadOrder[modIndex].Mod is null)
            throw new Exception($"{lightingMod} isn't loaded");

        var cells = state.LoadOrder[modIndex].Mod!
            .EnumerateMajorRecords<ICellGetter>()
            .ToDictionary(x => x.FormKey);

        foreach (var mod in state.LoadOrder.ListedOrder.Skip(modIndex + 1))
        {
            if (!mod.Enabled || mod.Mod is null || !mod.Mod.ModHeader.MasterReferences.Any(x => x.Master == lightingMod))
                continue;

            foreach (var cell in mod.Mod.EnumerateMajorRecords<ICellGetter>())
                if (cells.ContainsKey(cell.FormKey))
                    cells[cell.FormKey] = cell;
        }

        var mask = new Cell.TranslationMask(defaultOn: true)
        {
            FormKey = false,
            Landscape = new Landscape.TranslationMask(defaultOn: false, onOverall: false),
            NavigationMeshes = new NavigationMesh.TranslationMask(defaultOn: false, onOverall: false),
            Timestamp = false,
            UnknownGroupData = false,
            PersistentTimestamp = false,
            PersistentUnknownGroupData = false,
            Persistent = false,
            TemporaryTimestamp = false,
            TemporaryUnknownGroupData = false,
            Temporary = false
        };

        var winners = state.LoadOrder.PriorityOrder
            .Cell()
            .WinningContextOverrides(state.LinkCache)
            .ToDictionary(x => x.Record.FormKey);

        var existing = state.PatchMod
            .EnumerateMajorRecords<ICellGetter>()
            .Select(x => x.FormKey)
            .ToHashSet();

        var patched = 0;

        foreach (var (formKey, source) in cells)
        {
            if (!winners.TryGetValue(formKey, out var winner) || winner.Record.Equals(source, mask))
                continue;

            var wasThere = existing.Contains(formKey);
            var cell = winner.GetOrAddAsOverride(state.PatchMod);

            if (!wasThere)
            {
                cell.Landscape = null;
                cell.NavigationMeshes.Clear();
                cell.Persistent.Clear();
                cell.Temporary.Clear();
                cell.Timestamp = 0;
                cell.UnknownGroupData = 0;
                cell.PersistentTimestamp = 0;
                cell.PersistentUnknownGroupData = 0;
                cell.TemporaryTimestamp = 0;
                cell.TemporaryUnknownGroupData = 0;
            }

            ((ICellInternal)cell).DeepCopyIn(source, out _, mask);

            if (!wasThere)
                existing.Add(formKey);

            patched++;
        }

        Console.WriteLine($"Patched {patched} CELL headers from {lightingMod}");
    }
}
